**Data Extraction**

In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import requests as re

In [3]:
# from selenium import webdriver
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.by import By
# import time

In [4]:
df = pd.read_csv("IPL_Dataset(2008-2024).csv")

In [5]:
df.head()

,Match_ID,Date,Teams,Venue,Toss_Winner,Toss_Decision,Match_Winner,Win_Type,Win_Margin,First_Innings_Score,Second_Innings_Score,Player_of_Match,Umpire,Umpire1,Umpire2,Powerplay_Scores,Middle_Overs_Scores,Death_Overs_Scores
0,335982,2008-04-18,Royal Challengers Bangalore vs Kolkata Knight ...,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,222,82.0,BB McCullum,Asad Rauf,RE Koertzen,J Srinath,61,97,64
1,335983,2008-04-19,Kings XI Punjab vs Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,240,207.0,MEK Hussey,MR Benson,SL Shastri,S Venkataraghavan,53,116,71
2,335984,2008-04-19,Delhi Daredevils vs Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,129,132.0,MF Maharoof,Aleem Dar,GA Pratapkumar,GR Viswanath,40,66,23
3,335985,2008-04-20,Mumbai Indians vs Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,165,166.0,MV Boucher,SJ Davis,DJ Harper,J Srinath,47,71,47
4,335986,2008-04-20,Kolkata Knight Riders vs Deccan Chargers,Eden Gardens,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,110,112.0,DJ Hussey,BF Bowden,K Hariharan,FM Engineer,39,43,28

In [6]:
df.describe()

,Match_ID,Win_Margin,First_Innings_Score,Second_Innings_Score,Powerplay_Scores,Middle_Overs_Scores,Death_Overs_Scores
count,1.073000e+03,1054.000000,1073.000000,1070.000000,1073.000000,1073.000000,1073.000000
mean,8.941365e+05,17.158444,165.164958,151.918692,46.074557,78.248835,40.841566
std,3.637486e+05,21.762303,31.904238,31.751666,12.007306,18.604148,14.228121
min,3.359820e+05,1.000000,56.000000,2.000000,15.000000,0.000000,0.000000
25%,5.483260e+05,6.000000,145.000000,134.000000,38.000000,66.000000,33.000000
50%,9.809390e+05,8.000000,165.000000,153.000000,46.000000,77.000000,41.000000
75%,1.216540e+06,19.750000,186.000000,172.000000,53.000000,90.000000,50.000000
max,1.426287e+06,146.000000,287.000000,262.000000,125.000000,155.000000,89.000000

In [7]:
df.shape

(1073, 18)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Match_ID              1073 non-null   int64
 1   Date                  1073 non-null   object
 2   Teams                 1073 non-null   object
 3   Venue                 1073 non-null   object
 4   Toss_Winner           1073 non-null   object
 5   Toss_Decision         1073 non-null   object
 6   Match_Winner          1073 non-null   object
 7   Win_Type              1054 non-null   object
 8   Win_Margin            1054 non-null   float64
 9   First_Innings_Score   1073 non-null   int64
 10  Second_Innings_Score  1070 non-null   float64
 11  Player_of_Match       1068 non-null   object
 12  Umpire                1073 non-null   object
 13  Umpire1               1073 non-null   object
 14  Umpire2               1073 non-null   object
 15  Powerplay_Scores      1073 non-null   int64
 16  Middle_Overs_Scores   1073 non-null   int64
 17  Death_Overs_Scores    1073 non-null   int64
dtypes: float64(2), int64(5), object(11)
memory usage: 151.0+ KB

In [15]:
new_df = df[["Match_ID","Date","Teams","Date","Toss_Winner","Toss_Decision","Match_Winner"]].reset_index(drop=True)

In [16]:
new_df

,Match_ID,Date,Teams,Date,Toss_Winner,Toss_Decision,Match_Winner
0,335982,2008-04-18,Royal Challengers Bangalore vs Kolkata Knight ...,2008-04-18,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,335983,2008-04-19,Kings XI Punjab vs Chennai Super Kings,2008-04-19,Chennai Super Kings,bat,Chennai Super Kings
2,335984,2008-04-19,Delhi Daredevils vs Rajasthan Royals,2008-04-19,Rajasthan Royals,bat,Delhi Daredevils
3,335985,2008-04-20,Mumbai Indians vs Royal Challengers Bangalore,2008-04-20,Mumbai Indians,bat,Royal Challengers Bangalore
4,335986,2008-04-20,Kolkata Knight Riders vs Deccan Chargers,2008-04-20,Deccan Chargers,bat,Kolkata Knight Riders
...,...,...,...,...,...,...,...
1068,1426283,2024-04-28,Gujarat Titans vs Royal Challengers Bengaluru,2024-04-28,Royal Challengers Bengaluru,field,Royal Challengers Bengaluru
1069,1426284,2024-04-28,Chennai Super Kings vs Sunrisers Hyderabad,2024-04-28,Sunrisers Hyderabad,field,Chennai Super Kings
1070,1426285,2024-04-29,Delhi Capitals vs Kolkata Knight Riders,2024-04-29,Delhi Capitals,bat,Kolkata Knight Riders
1071,1426286,2024-04-30,Mumbai Indians vs Lucknow Super Giants,2024-04-30,Lucknow Super Giants,field,Lucknow Super Giants
1072,1426287,2024-05-01,Chennai Super Kings vs Punjab Kings,2024-05-01,Punjab Kings,field,Punjab Kings